name: deploy

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
  repository_dispatch:
    type: [repository_dispatch_event]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Run some script
        run: echo "Trigger by another repo"
        
