name: deploy

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
  repository_dispatch:
    types: [repository_dispatch_event]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run some script
        run: echo "Trigger by another repo"
